// System sizing runner (Node, not k6). Runs the chat scenario at stepped user
// counts against the compose stack with fixed per-container resource limits,
// samples CPU/RAM per service via `docker stats`, and generates docs/sizing.md —
// a capacity table (users → vCPU/RAM per service, recommended replica counts).
//
// Regenerate per release; this table doubles as the customer VPC deploy guide.
//
//   node --experimental-strip-types tests/load/sizing.ts
//   (or: npx tsx tests/load/sizing.ts)
import { execFileSync, spawn } from "node:child_process";
import { writeFileSync } from "node:fs";

const STEPS = [10, 25, 50, 100, 200];
const SERVICES = ["gateway", "redactor", "postgres", "redis"];
const GATEWAY_URL = process.env.GATEWAY_URL || "http://localhost:8080";

interface Sample {
  users: number;
  perService: Record<string, { cpuPct: number; memMb: number }>;
}

function dockerStatsOnce(): Record<string, { cpuPct: number; memMb: number }> {
  const out = execFileSync("docker", ["stats", "--no-stream", "--format", "{{.Name}} {{.CPUPerc}} {{.MemUsage}}"], { encoding: "utf8" });
  const map: Record<string, { cpuPct: number; memMb: number }> = {};
  for (const line of out.trim().split("\n")) {
    const [name, cpu, memUsage] = line.split(/\s+/);
    const svc = SERVICES.find((s) => name?.includes(s));
    if (!svc) continue;
    const memMb = parseMem(memUsage ?? "0MiB");
    map[svc] = { cpuPct: parseFloat((cpu ?? "0").replace("%", "")), memMb };
  }
  return map;
}

function parseMem(s: string): number {
  const m = /([\d.]+)([GMK]i?B)/.exec(s.split("/")[0]!.trim());
  if (!m) return 0;
  const v = parseFloat(m[1]!);
  return m[2]!.startsWith("G") ? v * 1024 : m[2]!.startsWith("K") ? v / 1024 : v;
}

async function runStep(users: number): Promise<Sample> {
  const child = spawn("k6", ["run", "--vus", String(users), "--duration", "90s", "tests/load/chat-users.ts"], {
    env: { ...process.env, GATEWAY_URL, HOLD: "90s" },
    stdio: "inherit",
  });
  const samples: Record<string, { cpuPct: number; memMb: number }>[] = [];
  const timer = setInterval(() => {
    try {
      samples.push(dockerStatsOnce());
    } catch {
      /* stats may momentarily fail */
    }
  }, 3000);
  await new Promise((r) => child.on("exit", r));
  clearInterval(timer);

  const perService: Sample["perService"] = {};
  for (const svc of SERVICES) {
    const svcSamples = samples.map((s) => s[svc]).filter(Boolean) as { cpuPct: number; memMb: number }[];
    perService[svc] = {
      cpuPct: Math.max(0, ...svcSamples.map((s) => s.cpuPct)),
      memMb: Math.max(0, ...svcSamples.map((s) => s.memMb)),
    };
  }
  return { users, perService };
}

function render(samples: Sample[]): string {
  let md = "# System sizing\n\n";
  md += "Generated by `tests/load/sizing.ts` against the compose stack with fixed per-container limits.\n";
  md += "Peak CPU / RAM per service by concurrent chat users. **Note:** the redactor holds spaCy models in memory (~1–2 GB/worker); size RAM per worker and set the users-per-worker ratio accordingly.\n\n";
  md += "| users | " + SERVICES.map((s) => `${s} CPU% / RAM`).join(" | ") + " |\n";
  md += "|---|" + SERVICES.map(() => "---").join("|") + "|\n";
  for (const s of samples) {
    md += `| ${s.users} | ` + SERVICES.map((svc) => `${s.perService[svc]!.cpuPct.toFixed(0)}% / ${s.perService[svc]!.memMb.toFixed(0)} MB`).join(" | ") + " |\n";
  }
  md += "\n## Recommended replicas (rule of thumb)\n";
  md += "- redactor: 1 replica per ~25 concurrent chat users (2 uvicorn workers each).\n";
  md += "- gateway: CPU-bound on crypto + streaming; scale on p95 first-token.\n";
  return md;
}

const results: Sample[] = [];
for (const users of STEPS) {
  console.log(`\n=== sizing step: ${users} users ===`);
  results.push(await runStep(users));
}
writeFileSync("docs/sizing.md", render(results));
console.log("wrote docs/sizing.md");
